
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Denilson
 */
public class RegistoForm extends javax.swing.JFrame {
    Vector x = new Vector();
    ImageIcon Ft = new ImageIcon();
    String Caminho=null;
ImageIcon conteudo=null;
//----------------------------Conexao Base de Dados---------------------------------
private String driver="com.mysql.jdbc.Driver";
private String url="jdbc:mysql://localhost:3306/sgv?zeroDateTimeBehavior=convertToNull";
private String user="root";
private String pass="";
private Connection con=null;
private Statement sta=null;
private ResultSet resultado=null; 
//-------------------___--------------___----------------------------___------------
    public RegistoForm() {
        initComponents();
         this.setLocationRelativeTo(null);
         this.setResizable(false);
         this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
         
         
         //--------------------------------------Source Cod ---------------------------
         cboSexo.addItem("Masculino");
         cboSexo.addItem("Feminino");
         cboSexo.setSelectedIndex(-1);
         
         
         cboFuncao.addItem("Administrador");
         cboFuncao.addItem("Usuario");
         cboFuncao.setSelectedIndex(-1);
         
         //0----------------------------------
         this.setTitle("Registar Usuario");
         //-----------------------------------------
        //-------------------------------------------------------------------------------------
       ImageIcon icone =new ImageIcon(this.getClass().getResource("folder/pic.jpg"));
       icone.setImage(icone.getImage().getScaledInstance(butFoto.getWidth(),butFoto.getHeight(),1)); 
       butFoto.setIcon(icone);
       //--------------------------------------------------------------------------------------
       //--------------------------------------------------------
        URL url=this.getClass().getResource("folder/JFR.png");
        Image i =Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(i); 
        
        jTable1.setRowHeight(20);
        //--------------------------------------------------------
        prencher();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox4 = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cboFuncao = new javax.swing.JComboBox();
        txtEndereco = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        cboSexo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtContacto = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        txtC = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonREG = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        butFoto = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(247, 247, 247));

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 13)); // NOI18N
        jLabel3.setText("Nivel:");

        cboFuncao.setBackground(new java.awt.Color(255, 255, 255));
        cboFuncao.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cboFuncao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { }));

        txtEndereco.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Consolas", 1, 13)); // NOI18N
        jLabel8.setText("Endereço: ");

        txtNome.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 13)); // NOI18N
        jLabel4.setText("Nome do Usuário:");

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 13)); // NOI18N
        jLabel5.setText("Palavra Passe:");

        jLabel6.setFont(new java.awt.Font("Consolas", 1, 13)); // NOI18N
        jLabel6.setText("Confirmação: ");

        jLabel12.setFont(new java.awt.Font("Consolas", 1, 13)); // NOI18N
        jLabel12.setText("E-mail:");

        txtEmail.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        cboSexo.setBackground(new java.awt.Color(255, 255, 255));
        cboSexo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cboSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] {  }));

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 13)); // NOI18N
        jLabel2.setText("Sexo:");

        jLabel7.setFont(new java.awt.Font("Consolas", 1, 13)); // NOI18N
        jLabel7.setText("Contacto:");

        jLabel13.setFont(new java.awt.Font("Consolas", 1, 13)); // NOI18N
        jLabel13.setText("Codigo:");

        txtCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodActionPerformed(evt);
            }
        });
        txtCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodKeyReleased(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon("E:\\Ficheiros\\Photos\\Icones Pack\\gif\\24x24\\Find.gif")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel13))
                                .addGap(12, 12, 12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(28, 28, 28)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cboSexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCod)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addGap(72, 72, 72))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtC, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel5)
                        .addGap(12, 12, 12)
                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(cboFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel5))
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel3.setOpaque(false);

        jButtonREG.setBackground(new java.awt.Color(255, 255, 255));
        jButtonREG.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButtonREG.setIcon(new javax.swing.ImageIcon("E:\\Ficheiros\\Photos\\Icones Pack\\gif\\24x24\\Save.gif")); // NOI18N
        jButtonREG.setText(" Gravar");
        jButtonREG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonREG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonREGActionPerformed(evt);
            }
        });

        jButtonVoltar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonVoltar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButtonVoltar.setIcon(new javax.swing.ImageIcon("E:\\Ficheiros\\Photos\\Icones Pack\\gif\\24x24\\Add.gif")); // NOI18N
        jButtonVoltar.setText(" Adicionar");
        jButtonVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("E:\\Ficheiros\\Photos\\Icones Pack\\gif\\24x24\\Modify.gif")); // NOI18N
        jButton1.setText(" Atualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Relatorio/Delete.png"))); // NOI18N
        jButton2.setText(" Apagar ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("E:\\Ficheiros\\Photos\\Icones Pack\\gif\\24x24\\Lock.gif")); // NOI18N
        jButton3.setText(" Login ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon("E:\\Ficheiros\\Photos\\Icones Pack\\png\\24x24\\Home.png")); // NOI18N
        jButton4.setText(" Menu");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jButtonREG, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addGap(31, 31, 31)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonREG, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel4.setOpaque(false);

        jTable1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo:", "Nome do Usuário ", "Contacto:", "Sexo  ", " Função: ", " Endereço:"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(80);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(1).setMinWidth(270);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(280);
            jTable1.getColumnModel().getColumn(2).setMinWidth(100);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(120);
            jTable1.getColumnModel().getColumn(3).setMinWidth(150);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(160);
            jTable1.getColumnModel().getColumn(4).setMinWidth(140);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(160);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Consolas", 1, 13)); // NOI18N
        jLabel9.setText("Botões de Operações");

        jLabel10.setFont(new java.awt.Font("Consolas", 1, 13)); // NOI18N
        jLabel10.setText("Informação do Usuario");

        jLabel11.setFont(new java.awt.Font("Consolas", 1, 13)); // NOI18N
        jLabel11.setText("Foto do Usuário ");

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 13)); // NOI18N
        jLabel1.setText("Visualização dos usuários Cadastrados");

        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel5.setOpaque(false);

        butFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butFotoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(butFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap(918, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 503, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
      jButtonVoltar.setForeground(Color.green);
        txtNome.setText(null); txtC.setText(null);
       
        txtSenha.setText(null);
       
        JOptionPane.showMessageDialog(null,"Campos Limpos");
        
        jButtonVoltar.setForeground(Color.black);
       
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonREGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonREGActionPerformed
     //VAlidadcao Imediata dos Campos Todos
         if(txtNome.getText().length()!=0 && txtSenha.getText().length()!=0&&txtC.getText().length()!=0&&
      txtContacto.getText().length()!=0&&cboSexo.getSelectedItem().toString().length()!=0&&
      cboFuncao.getSelectedItem().toString().length()!=0&&txtEndereco.getText().length()!=0&& 
      txtEmail.getText().length()!=0){
             
        
        this.insert(txtNome.getText(),txtSenha.getText(),txtC.getText(),Integer.parseInt(txtContacto.getText()),
             cboSexo.getSelectedItem().toString(),cboFuncao.getSelectedItem().toString(),txtEndereco.getText(),
             txtEmail.getText(),cboFuncao.getSelectedItem().toString());
        
        
         }else{JOptionPane.showMessageDialog(null,"Verifique se Preencheu todos Campos Disponiveis! Por f"
                 + "avor");}
    }//GEN-LAST:event_jButtonREGActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        if(txtCod.getText().length()!=0){
            
        update(); 
        
        }else{JOptionPane.showMessageDialog(null, "Preencha o campo codigo");}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        LoginForm f = new LoginForm();
        f.setVisible(true);
        f.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void butFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butFotoMouseClicked
         butFoto.setIcon(foto());     
    }//GEN-LAST:event_butFotoMouseClicked

    private void txtNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyReleased
      
    }//GEN-LAST:event_txtNomeKeyReleased

    private void txtCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodActionPerformed

    private void txtCodKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodKeyReleased
        Procurar();
    }//GEN-LAST:event_txtCodKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if(txtCod.getText().length()!=0){
           
        this.delete(Integer.parseInt(txtCod.getText())); 
        
       }else{JOptionPane.showMessageDialog(null,"Verifique se o campo codigo esta Preenchido!");}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      int indice=jTable1.getSelectedRow();
      TableModel model = jTable1.getModel();
      this.index(indice); 
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
//        Menu a = new Menu();
//        a.setVisible(true);
//        a.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton4ActionPerformed

    public void index(int inde){
    LoginS a;
    
    a=(LoginS)x.get(inde);  
       mostra(a);
    
    }
    
    
    
    public void insert (String nome,String senha,String conf,int cont,String sexo,String funcao,String end,String email,String Nivel){
        
       try{
//  
       
           Class.forName(driver);
           
          this.con=DriverManager.getConnection(url, user, pass);
           sta=con.createStatement();
            if(txtSenha.getText().equals(txtC.getText())){
           String query1="insert into usuario (nome_User,Senha,Co_Senha,contacto_User,Sexo,funcao,endereco,Email,foto,Nivel) VALUES"
                   + " ('"+nome+"','"+senha +"','"+conf+"','"+cont+"','"+sexo+"','"+funcao+"','"+end+"','"+email+"','"+w+"','"+Nivel+"')";
           sta.execute(query1);
           
           
           JOptionPane.showMessageDialog(null, "Usuario Registado com Sucesso!!");Codigo();prencher();
           
            }else {JOptionPane.showMessageDialog(null,"A senha nao Corresponde a confirmacao da senha");}
            
            
        
       }catch(SQLException e){
           JOptionPane.showMessageDialog(null, "Falha no Registo User","Registo", JOptionPane.ERROR_MESSAGE);
           //System.out.println(e);
       }catch(ClassNotFoundException e){
         JOptionPane.showMessageDialog(null, "Driver ");  
       }
       catch(NumberFormatException e){
           JOptionPane.showMessageDialog(null, "Erro de numero"); 
       }
       
    
}
    
    
 public void Codigo(){
        
           try {
        
           Class.forName(driver);
           
          this.con=DriverManager.getConnection(url, user, pass);
           sta=con.createStatement();
         
         String query8="select id_user from usuario where nome_User='"+txtNome.getText()+"'";
            
          this.resultado=sta.executeQuery(query8);
            
          while(resultado.next()){      
           
             txtCod.setText(resultado.getInt("id_user")+"");
           //  JOptionPane.showMessageDialog(null,"Cheguei AQui De novo" );
            }
          
       }catch(SQLException e){
           JOptionPane.showMessageDialog(null, "Falha na busca do codigo","Pesquisa", JOptionPane.ERROR_MESSAGE);
           System.out.println(e);
       }catch(ClassNotFoundException e){
         JOptionPane.showMessageDialog(null, "Driver ");  
       }
       catch(NumberFormatException e){
           JOptionPane.showMessageDialog(null, "numerFoto"); 
       }  
           catch(NullPointerException e){ 
           JOptionPane.showMessageDialog(null, "Falha na busca do codigo"); 
       }  
               
    }
    
    
    
    
String w="C:/Users/Junior Cua/Documents/NetBeansProjects/LoginS/foto/Usuario/User.png";
public ImageIcon foto(){
    try{
        
    JFileChooser choose = new JFileChooser("C:/Users/Junior Cua/Documents/NetBeansProjects/LoginS/foto/Usuario/");
    
   int ok=choose.showOpenDialog(null);
   
   if(ok==choose.APPROVE_OPTION){
       
   Caminho=choose.getSelectedFile().getName();
  
   w="C:/Users/Junior Cua/Documents/NetBeansProjects/LoginS/foto/Usuario/"+Caminho;
   
   conteudo=new ImageIcon(w);
   
   conteudo.setImage(conteudo.getImage().getScaledInstance(butFoto.getWidth(),butFoto.getHeight(),1));
    
   Ft=conteudo;
   
    
   File f= choose.getSelectedFile(); 
       
   }else{
       choose.cancelSelection();
   }
    }catch(Exception e){
        e.printStackTrace();
    }
    //---Atualizar Foto-------------
      updateFoto();
    //--------------
     return conteudo;
}
    
    
    
    public void updateFoto (){
       try{
            try {
           Class.forName(driver);
           
          this.con=DriverManager.getConnection(url, user, pass);
           sta=con.createStatement();
           
           String queryS="UPDATE usuario SET "
                   + "foto='"+w+"'"     
                   + "WHERE nome_User='"+txtNome.getText()+"'";
           
           sta.execute(queryS);
          prencher();
          // JOptionPane.showMessageDialog(null, "Foto Atualizada com sucesso");  
       }catch(SQLException e){
           JOptionPane.showMessageDialog(null, "Falha ao atualizar dados \n"
                   + "Descricao: "+e+"","Atualizacao", JOptionPane.ERROR_MESSAGE);
           
       }catch(ClassNotFoundException e){
         JOptionPane.showMessageDialog(null, "Driver ");  
       }
       } catch (Exception e) {  }
   }
   
    
    
    
    
    
    
 public void prencher(){
    LoginS a;
    try{
                     
           Class.forName(driver);
           //--------------------Limpando tabela----------------------------
           DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
           
          ((DefaultTableModel)jTable1.getModel()).setNumRows(0); 
          
           jTable1.updateUI(); 
           //---------------------------------------------------------------
           //---------------------------------------------------------------
           //Limpando Vector
             for(int i =0;i<x.size();i++){
             x.removeAllElements();
             }
         //---------------------------------------------------------------- 
          
           String [] linha= new String [6];
           
          this.con=DriverManager.getConnection(url, user, pass);
          sta=con.createStatement();

         String query2="select * from usuario order by id_user asc";
            
          this.resultado=sta.executeQuery(query2);
            
          while(resultado.next()){
        //------------------------------------------------------------------------
         vectorFood(resultado.getInt("id_user"),resultado.getString("nome_User"),resultado.getString("Senha"),
         resultado.getString("Co_Senha"),
         resultado.getInt("contacto_User"),resultado.getString("Email"),resultado.getString("endereco"),
         resultado.getString("foto"),resultado.getString("Nivel"),resultado.getString("sexo"));
         //----------------------------------------------------------------------------------
              
            linha[0]=resultado.getInt("id_user")+"";
            linha[1]=resultado.getString("nome_User");
            linha[2]=resultado.getString("contacto_User");
            linha[3]=resultado.getString("sexo");
            linha[4]=resultado.getString("funcao"); 
            linha[5]=resultado.getString("endereco"); 
          
           model.addRow(linha);
           
            }
       }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Falha no preenchimento da tabela","Pesquisa", JOptionPane.ERROR_MESSAGE);
           System.out.println(e);
       }catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(null, "Driver ");  
       }
       catch(NumberFormatException e){
           JOptionPane.showMessageDialog(null, "numero"); 
       }      
    }
       
    
 
 
 
 
 
 
 int c=0;
 public void Procurar(){
        
           try {
               
           //-------------------------------
           txtNome.setText(null);
           txtSenha.setText(null);
           cboSexo.setSelectedIndex(-1); 
           cboFuncao.setSelectedIndex(-1);
           txtC.setText(null);
           txtContacto.setText(null);
           txtEmail.setText(null);
           txtEndereco.setText(null);
           
            //-------------------------------------------------------------------------------------
       ImageIcon icone =new ImageIcon(this.getClass().getResource("folder/pic.jpg"));
       icone.setImage(icone.getImage().getScaledInstance(butFoto.getWidth(),butFoto.getHeight(),1)); 
       butFoto.setIcon(icone);
       //--------------------------------------------------------------------------------------
           Class.forName(driver);
           
          this.con=DriverManager.getConnection(url, user, pass);
           sta=con.createStatement();
         if(txtCod.getText().length()!=0){
         String query5="select * from usuario where id_user = '"+Integer.parseInt(txtCod.getText())+"'";
            
          this.resultado=sta.executeQuery(query5);
            
          while(resultado.next()){                        
                                
             txtNome.setText(resultado.getString("nome_User")); 
             txtSenha.setText(resultado.getString("Senha")+"");
             cboSexo.setSelectedItem(resultado.getString("sexo" ));
             txtC.setText(resultado.getString("Co_Senha"));
             txtContacto.setText(resultado.getInt("contacto_user")+"");
             txtEmail.setText(resultado.getString("Email"));
             txtEndereco.setText(resultado.getString("endereco"));
             cboFuncao.setSelectedItem(resultado.getString("funcao"));
             butFoto.setIcon(fotoP(resultado.getString("foto")));
                
              c++;
            }prencher();
           if(c==0){                          }  
          
         } else{} 
           
       }catch(SQLException e){
           JOptionPane.showMessageDialog(null, "Falha na busca dos Produtos","Pesquisa", JOptionPane.ERROR_MESSAGE);
           System.out.println(e);
       }catch(ClassNotFoundException e){
         JOptionPane.showMessageDialog(null, "Driver ");  
       }
       catch(NumberFormatException e){
           JOptionPane.showMessageDialog(null, "numero"); 
       }  
           catch(NullPointerException e){ 
           JOptionPane.showMessageDialog(null, "Falha na busca da foto"); 
       }  
        
       catch (Exception e) {JOptionPane.showMessageDialog(null,"Verifique os campos"); 
       }
        
    }
    
 
 
 
 
 
    public ImageIcon fotoP(String Way){
       
    try{
        
   conteudo=new ImageIcon(Way);
   
   conteudo.setImage(conteudo.getImage().getScaledInstance(butFoto.getWidth(),butFoto.getHeight(),1));
   
  }catch(Exception e){
        e.printStackTrace();
   }
     return conteudo;
}
    
    
    
  public void update (){
       try{
            try {
           Class.forName(driver);
           
          this.con=DriverManager.getConnection(url, user, pass);
           sta=con.createStatement();
           if(txtSenha.getText().equals(txtC.getText())){
               
           String queryS="UPDATE usuario SET "
                   + "nome_User ='"+txtNome.getText()+"',"
                   + "Senha='"+txtSenha.getText()+"',"
                   + "Co_Senha='"+txtC.getText()+"',"
                   + "contacto_User='"+Integer.parseInt(txtContacto.getText())+"',"
                   + "Sexo='"+cboSexo.getSelectedItem().toString()+"',"
                   + "funcao='"+cboFuncao.getSelectedItem().toString()+"',"
                   + "endereco='"+txtEndereco.getText()+"'," 
                   + "Nivel='"+cboFuncao.getSelectedItem().toString()+"',"  
                   + "Email='"+txtEmail.getText()+"'"  
                   + "WHERE id_user='"+Integer.parseInt(txtCod.getText())+"'"; 
           
           sta.execute(queryS);
           JOptionPane.showMessageDialog(null, "Usuario Actualizado");  prencher();
           
           } else {JOptionPane.showMessageDialog(null,"A senha nao Corresponde a confirmacao da senha");}
          
           
       }catch(SQLException e){
           JOptionPane.showMessageDialog(null, "Falha ao atualizar dados","Atualizacao", JOptionPane.ERROR_MESSAGE);
           System.out.println(e);
       }catch(ClassNotFoundException e){
         JOptionPane.showMessageDialog(null, "Driver ");  
       }
       catch(NumberFormatException e){
           JOptionPane.showMessageDialog(null, "numero"); 
       }
       } catch (Exception e) {JOptionPane.showMessageDialog(null,"Verifique os campos"); 
       }
   }
   
    
   public void delete (int cod){
       try{
            try {
           Class.forName(driver);
           
          this.con=DriverManager.getConnection(url, user, pass);
           sta=con.createStatement();

           String query1=" delete from usuario where id_user = '"+cod+"'"; 
         
           sta.execute(query1);
           
           //-------------------------------
           txtNome.setText(null);
           txtSenha.setText(null);
           cboSexo.setSelectedIndex(-1); 
           cboFuncao.setSelectedIndex(-1);
           txtC.setText(null);
           txtContacto.setText(null);
           txtEmail.setText(null);
           txtEndereco.setText(null);
           txtCod.setText(null);
           
            //-------------------------------------------------------------------------------------
       ImageIcon icone =new ImageIcon(this.getClass().getResource("folder/pic.jpg"));
       icone.setImage(icone.getImage().getScaledInstance(butFoto.getWidth(),butFoto.getHeight(),1)); 
       butFoto.setIcon(icone);
       //--------------------------------------------------------------------------------------
       
       
           JOptionPane.showMessageDialog(null, "Usuario Eliminado"); this.prencher();
       }catch(SQLException e){
           JOptionPane.showMessageDialog(null, "Falha ao eliminar Usuario","Eliminar", JOptionPane.ERROR_MESSAGE);
           
       }catch(ClassNotFoundException e){
         JOptionPane.showMessageDialog(null, "Driver ");  
       }
       catch(NumberFormatException e){
           JOptionPane.showMessageDialog(null, "Falha de numero"); 
       }
             } catch (Exception e) {JOptionPane.showMessageDialog(null,"Verifique os campos"); 
       }
       
   }
         
  
  
  //---------------------------------Usando Vector------------------------------------------------------------------------------
      public void vectorFood(int codU,String NomeU,String SenhaU, String ConU,int contacto,String email, String endereco,String Foto,String Nivel,String Sexo){
         LoginS a = new LoginS();
       
         a.codigoU=codU;
         a.nomeU=NomeU;
         a.SenhaU=SenhaU;
         a.CSenhaU=ConU;
         a.ContactoU=contacto;
         a.EmailU=email;
         a.EndeU=endereco;
         a.FotoU=Foto;
         a.SexoU=Sexo;
         a.nivelU=Nivel;
         
         x.addElement(a);
    }
  
      public void mostra(LoginS a ){
       
      txtCod.setText(a.codigoU+"");
      txtNome.setText(a.nomeU);
      txtContacto.setText(a.ContactoU+"");
      txtEmail.setText(a.EmailU);
      txtSenha.setText(a.SenhaU);
      txtC.setText(a.CSenhaU);
      cboSexo.setSelectedItem(a.SexoU);
      cboFuncao.setSelectedItem(a.nivelU);
      txtEndereco.setText(a.EndeU);      
      butFoto.setIcon(this.fotoP(a.FotoU)); 
     }
  
  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel butFoto;
    private javax.swing.JComboBox cboFuncao;
    private javax.swing.JComboBox cboSexo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonREG;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtC;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtContacto;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables
}
