
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Antonio Cua
 */
public class Fornecedor extends javax.swing.JFrame {

    Vector x = new Vector();
    ImageIcon Ft = new ImageIcon();
    String Caminho = null;
    ImageIcon conteudo = null;
//----------------------------Conexao Base de Dados---------------------------------
    private String driver = "com.mysql.jdbc.Driver";
    private String url = "jdbc:mysql://localhost:3306/sgv?zeroDateTimeBehavior=convertToNull";
    private String user = "root";
    private String pass = "";
    private Connection con = null;
    private Statement sta = null;
    private ResultSet resultado = null;
//-------------------___--------------___----------------------------___------------

    public Fornecedor() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Registar Fornecedor");
        this.setResizable(false);
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        //-------------------------------------------------------------------------------------
        ImageIcon icone = new ImageIcon(this.getClass().getResource("folder/pic.jpg"));
        icone.setImage(icone.getImage().getScaledInstance(butFoto.getWidth(), butFoto.getHeight(), 1));
        butFoto.setIcon(icone);
       //--------------------------------------------------------------------------------------
        //--------------------------------------------------------
        URL url = this.getClass().getResource("folder/JFR.png");
        Image i = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(i);
        jTable1.setRowHeight(18);
        //--------------------------------------------------------

        prencher();

    }

    String w = "C:/Users/Junior Cua/Documents/NetBeansProjects/LoginS/foto/fornecedor/User.png";

    public ImageIcon foto() {
        try {

            JFileChooser choose = new JFileChooser("C:/Users/Junior Cua/Documents/NetBeansProjects/LoginS/foto/fornecedor/");

            int ok = choose.showOpenDialog(null);

            if (ok == choose.APPROVE_OPTION) {

                Caminho = choose.getSelectedFile().getName();

                w = "C:/Users/Junior Cua/Documents/NetBeansProjects/LoginS/foto/fornecedor/" + Caminho;

                conteudo = new ImageIcon(w);

                conteudo.setImage(conteudo.getImage().getScaledInstance(butFoto.getWidth(), butFoto.getHeight(), 1));

                Ft = conteudo;

                File f = choose.getSelectedFile();

            } else {
                choose.cancelSelection();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        //---Atualizar Foto-------------
        updateFoto();
        //--------------
        return conteudo;
    }

    public void updateFoto() {
        try {
            try {
                Class.forName(driver);

                this.con = DriverManager.getConnection(url, user, pass);
                sta = con.createStatement();

                String queryS = "UPDATE fornecedor SET "
                        + "foto='" + w + "'"
                        + "WHERE Nome='" + txtNome.getText() + "'";

                sta.execute(queryS);
                prencher();
                //JOptionPane.showMessageDialog(null, "Foto buscada com sucesso");  
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Falha ao atualizar Foto", "Atualizacao", JOptionPane.ERROR_MESSAGE);
                System.out.println(e);
            } catch (ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null, "Driver ");
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        butFoto = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtContacto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEnde = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        butApagar = new javax.swing.JButton();
        butAtualizar = new javax.swing.JButton();
        butRegistar = new javax.swing.JButton();
        butadd = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(247, 247, 247));

        jPanel2.setOpaque(false);

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel3.setOpaque(false);

        butFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butFotoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(butFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(butFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel4.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 13)); // NOI18N
        jLabel1.setText("Codigo:");

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 13)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 13)); // NOI18N
        jLabel3.setText("Contacto:");

        txtCod.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodActionPerformed(evt);
            }
        });
        txtCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodKeyReleased(evt);
            }
        });

        txtNome.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N

        txtContacto.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 13)); // NOI18N
        jLabel4.setText("E-Mail:");

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 13)); // NOI18N
        jLabel5.setText("Bairro: ");

        txtemail.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N

        txtEnde.setColumns(20);
        txtEnde.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtEnde.setRows(5);
        jScrollPane1.setViewportView(txtEnde);

        jLabel14.setIcon(new javax.swing.ImageIcon("E:\\Ficheiros\\Photos\\Icones Pack\\gif\\24x24\\Find.gif")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtNome)
                                .addGap(28, 28, 28)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(42, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Consolas", 1, 13)); // NOI18N
        jLabel7.setText("Informações do Fornecedor ");

        jLabel8.setFont(new java.awt.Font("Consolas", 1, 13)); // NOI18N
        jLabel8.setText("Foto do fornecedor");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5)))
                .addGap(5, 5, 5))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setOpaque(false);

        jScrollPane2.setOpaque(true);

        jTable1.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo:", "Nome:", "Contacto:", "Email:", "Bairro: ", "Data:"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(60);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(80);
            jTable1.getColumnModel().getColumn(2).setMinWidth(110);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(120);
            jTable1.getColumnModel().getColumn(5).setMinWidth(180);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(190);
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
        );

        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel6.setOpaque(false);

        butApagar.setBackground(new java.awt.Color(255, 255, 255));
        butApagar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        butApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/Deletes.png"))); // NOI18N
        butApagar.setText(" Eliminar");
        butApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butApagarActionPerformed(evt);
            }
        });

        butAtualizar.setBackground(new java.awt.Color(255, 255, 255));
        butAtualizar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        butAtualizar.setIcon(new javax.swing.ImageIcon("E:\\Ficheiros\\Photos\\Icones Pack\\gif\\24x24\\Modify.gif")); // NOI18N
        butAtualizar.setText(" Atualizar");
        butAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAtualizarActionPerformed(evt);
            }
        });

        butRegistar.setBackground(new java.awt.Color(255, 255, 255));
        butRegistar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        butRegistar.setIcon(new javax.swing.ImageIcon("E:\\Ficheiros\\Photos\\Icones Pack\\gif\\24x24\\Save.gif")); // NOI18N
        butRegistar.setText(" Registar");
        butRegistar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRegistarActionPerformed(evt);
            }
        });

        butadd.setBackground(new java.awt.Color(255, 255, 255));
        butadd.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        butadd.setIcon(new javax.swing.ImageIcon("E:\\Ficheiros\\Photos\\Icones Pack\\gif\\24x24\\Add.gif")); // NOI18N
        butadd.setText(" Adicionar");
        butadd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaddActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("E:\\Ficheiros\\Photos\\Icones Pack\\png\\24x24\\Home.png")); // NOI18N
        jButton1.setText("Menu>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(butRegistar)
                .addGap(30, 30, 30)
                .addComponent(butAtualizar)
                .addGap(39, 39, 39)
                .addComponent(butApagar)
                .addGap(40, 40, 40)
                .addComponent(butadd, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butRegistar)
                    .addComponent(butAtualizar)
                    .addComponent(butApagar)
                    .addComponent(butadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Consolas", 1, 13)); // NOI18N
        jLabel9.setText("Botões de Operações");

        jLabel11.setFont(new java.awt.Font("Consolas", 1, 13)); // NOI18N
        jLabel11.setText("Fornecedores Registados");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactoActionPerformed

    private void txtCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodActionPerformed

    private void butApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butApagarActionPerformed
        if (txtCod.getText().length() != 0) {
            delete(Integer.parseInt(txtCod.getText()));
        } else {
            JOptionPane.showMessageDialog(null, "Verifique se o campo codigo esta preenchido", "Falha ao Eliminar", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_butApagarActionPerformed

    private void butAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAtualizarActionPerformed
        if (txtCod.getText().length() != 0) {
            update();
        } else {
            JOptionPane.showMessageDialog(null, "Verifique se o campo codigo esta preenchido", "Falha ao Atualizar", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_butAtualizarActionPerformed

    private void butRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRegistarActionPerformed
      if(txtNome.getText().length()!=0&&txtContacto.getText().length()!=0&&txtemail.getText().length()!=0&&txtEnde.getText().length()!=0){
            Registar();
      }else{JOptionPane.showMessageDialog(null,"Verifique se todos os campos estao Preenchidos!!","Erro",JOptionPane.ERROR_MESSAGE);}
    }//GEN-LAST:event_butRegistarActionPerformed

    private void butaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaddActionPerformed
//-------------------------------
        butadd.setBackground(Color.green);

        txtNome.setText(null);
        txtContacto.setText(null);
        txtemail.setText(null);
        txtEnde.setText(null);
        txtCod.setText(null);

        //-------------------------------------------------------------------------------------
        ImageIcon icone = new ImageIcon(this.getClass().getResource("folder/pic.jpg"));
        icone.setImage(icone.getImage().getScaledInstance(butFoto.getWidth(), butFoto.getHeight(), 1));
        butFoto.setIcon(icone);
        //--------------------------------------------------------------------------------------
        JOptionPane.showMessageDialog(null, "Campos Limpos");
        butadd.setBackground(Color.white);

    }//GEN-LAST:event_butaddActionPerformed

    private void butFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butFotoMouseClicked
        butFoto.setIcon(foto());
    }//GEN-LAST:event_butFotoMouseClicked

    private void txtCodKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodKeyReleased
        Procurar();
    }//GEN-LAST:event_txtCodKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
//        Menu a = new Menu();
//        a.setVisible(true);
//        a.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int indice = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        this.index(indice);
    }//GEN-LAST:event_jTable1MouseClicked

    public void index(int inde) {
        LoginS a;

        a = (LoginS) x.get(inde);
        mostra(a);

    }

    public void Registar() {

        LoginS a = new LoginS();
        try {
            Class.forName(driver);

            this.con = DriverManager.getConnection(url, user, pass);
            sta = con.createStatement();

            String Ins = "insert into fornecedor ( Nome,contacto,Email,endereco,foto) VALUES "
                    + "('" + txtNome.getText() + "','" + Integer.parseInt(txtContacto.getText()) + "','" + txtemail.getText() + "','" + txtEnde.getText() + ""
                    + "','" + w + "')";

            sta.execute(Ins);

            JOptionPane.showMessageDialog(null, "Fornecedor Registado com Sucesso!");
            Codigo();
            prencher();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Nao foi possivel Registar o fornecedor /n" + e, "Erro de Registo", JOptionPane.ERROR_MESSAGE);

        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Driver ");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Falha de Numero");
            System.out.println(e);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Verifique se preencheu os campos todos!!");
        }
    }

    public void prencher() {
        LoginS a;
        try {

            Class.forName(driver);
            //--------------------Limpando tabela----------------------------
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

            ((DefaultTableModel) jTable1.getModel()).setNumRows(0);

            jTable1.updateUI();
           //---------------------------------------------------------------
            //---------------------------------------------------------------
            //Limpando Vector
            for (int i = 0; i < x.size(); i++) {
                x.removeAllElements();
            }
         //---------------------------------------------------------------- 

            String[] linha = new String[6];

            this.con = DriverManager.getConnection(url, user, pass);
            sta = con.createStatement();

            String query2 = "select * from fornecedor order by id_for asc";

            this.resultado = sta.executeQuery(query2);

            while (resultado.next()) {
                //--------------------------------------------------------------------------------------------------
                vectorFood(resultado.getInt("id_for"), resultado.getString("Nome"), resultado.getInt("contacto"),
                        resultado.getString("Email"), resultado.getString("endereco"), resultado.getString("foto"));

          //---------------------------------------------------------------------------------------------------
                linha[0] = resultado.getInt("id_for") + "";
                linha[1] = resultado.getString("Nome");
                linha[2] = resultado.getString("contacto");
                linha[3] = resultado.getString("Email");
                linha[4] = resultado.getString("endereco");
                linha[5] = resultado.getString("Data");

                model.addRow(linha);

            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Falha no preenchimento da tabela", "Pesquisa", JOptionPane.ERROR_MESSAGE);

        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Driver ");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "numero");
        }
    }

    int c = 0;

    public void Procurar() {

        try {

            //-------------------------------
            txtNome.setText(null);
            txtContacto.setText(null);
            txtemail.setText(null);
            txtEnde.setText(null);

            //-------------------------------------------------------------------------------------
            ImageIcon icone = new ImageIcon(this.getClass().getResource("folder/pic.jpg"));
            icone.setImage(icone.getImage().getScaledInstance(butFoto.getWidth(), butFoto.getHeight(), 1));
            butFoto.setIcon(icone);
            //--------------------------------------------------------------------------------------
            Class.forName(driver);

            this.con = DriverManager.getConnection(url, user, pass);
            sta = con.createStatement();
            if (txtCod.getText().length() != 0) {
                String query5 = "select * from fornecedor where id_for = '" + Integer.parseInt(txtCod.getText()) + "'";

                this.resultado = sta.executeQuery(query5);

                while (resultado.next()) {

                    txtNome.setText(resultado.getString("Nome"));
                    txtCod.setText(resultado.getInt("id_for") + "");
                    txtEnde.setText(resultado.getString("endereco"));
                    txtemail.setText(resultado.getString("Email"));
                    txtContacto.setText(resultado.getInt("contacto") + "");
                    butFoto.setIcon(fotoP(resultado.getString("foto")));

                    c++;
                }
                prencher();
                if (c == 0) {
                }

            } else {
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Falha na busca do Fornecedor", "Pesquisa", JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Driver ");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "numero");
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Falha na busca da foto");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Verifique os campos");
        }

    }

    public void Codigo() {

        try {

            Class.forName(driver);

            this.con = DriverManager.getConnection(url, user, pass);
            sta = con.createStatement();

            String query8 = "select id_for from fornecedor where Nome='" + txtNome.getText() + "'";

            this.resultado = sta.executeQuery(query8);

            while (resultado.next()) {

                txtCod.setText(resultado.getInt("id_for") + "");
                //  JOptionPane.showMessageDialog(null,"Cheguei AQui De novo" );
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Falha na busca do codigo", "Pesquisa", JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Driver ");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "numerFoto");
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Falha na busca da foto");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Verifique os campos");
        }

    }

    public ImageIcon fotoP(String Way) {

        try {

            conteudo = new ImageIcon(Way);

            conteudo.setImage(conteudo.getImage().getScaledInstance(butFoto.getWidth(), butFoto.getHeight(), 1));

        } catch (Exception e) {
            e.printStackTrace();
        }
        return conteudo;
    }

    public void update() {
        try {
            try {
                Class.forName(driver);

                this.con = DriverManager.getConnection(url, user, pass);
                sta = con.createStatement();

                String queryS = "UPDATE fornecedor SET "
                        + "Nome ='" + txtNome.getText() + "',"
                        + "Email='" + txtemail.getText() + "',"
                        + "contacto='" + Integer.parseInt(txtContacto.getText()) + "',"
                        + "endereco='" + txtEnde.getText() + "'"
                        + "WHERE id_for='" + Integer.parseInt(txtCod.getText()) + "'";

                sta.execute(queryS);
                JOptionPane.showMessageDialog(null, "Usuario Actualizado");
                prencher();

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Falha ao atualizar dados", "Atualizacao", JOptionPane.ERROR_MESSAGE);
                System.out.println(e);
            } catch (ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null, "Driver ");
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "numero");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Verifique os campos");
        }
    }

    public void delete(int cod) {
        try {
            try {
                Class.forName(driver);

                this.con = DriverManager.getConnection(url, user, pass);
                sta = con.createStatement();

                String query1 = " delete from fornecedor where id_for = '" + cod + "'";

                sta.execute(query1);

                //-------------------------------
                txtNome.setText(null);
                txtContacto.setText(null);
                txtemail.setText(null);
                txtEnde.setText(null);
                txtCod.setText(null);

                //-------------------------------------------------------------------------------------
                ImageIcon icone = new ImageIcon(this.getClass().getResource("folder/pic.jpg"));
                icone.setImage(icone.getImage().getScaledInstance(butFoto.getWidth(), butFoto.getHeight(), 1));
                butFoto.setIcon(icone);
       //--------------------------------------------------------------------------------------

                JOptionPane.showMessageDialog(null, "Usuario Eliminado");
                this.prencher();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Falha ao eliminar Usuario", "Eliminar", JOptionPane.ERROR_MESSAGE);

            } catch (ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null, "Driver ");
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Falha de numero");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Verifique os campos");
        }

    }

    //---------------------------------Usando Vector------------------------------------------------------------------------------
    public void vectorFood(int codigo, String Nome, int contacto, String email, String endereco, String Foto) {
        LoginS a = new LoginS();

        a.For = codigo;
        a.nomeF = Nome;
        a.ContactoF = contacto;

        a.EmailF = email;
        a.enderecoF = endereco;
        a.fotoF = Foto;

        x.addElement(a);
    }

    public void mostra(LoginS a) {

        txtCod.setText(a.For + "");
        txtNome.setText(a.nomeF);
        txtContacto.setText(a.ContactoF + "");
        txtemail.setText(a.EmailF);
        txtEnde.setText(a.enderecoF);
        butFoto.setIcon(this.fotoP(a.fotoF));
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butApagar;
    private javax.swing.JButton butAtualizar;
    private javax.swing.JLabel butFoto;
    private javax.swing.JButton butRegistar;
    private javax.swing.JButton butadd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtContacto;
    private javax.swing.JTextArea txtEnde;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtemail;
    // End of variables declaration//GEN-END:variables
}
