

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.util.Date;

import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Antonio Cua
 */
public class History extends javax.swing.JFrame {
 Vector x = new Vector();
    
//----------------------------Conexao Base de Dados---------------------------------
private String driver="com.mysql.jdbc.Driver";
private String url="jdbc:mysql://localhost:3306/sgv?zeroDateTimeBehavior=convertToNull";
private String user="root";
private String pass="";
private Connection con=null;
private Statement sta=null;
private ResultSet resultado=null; 
//-------------------___--------------___----------------------------___------------ 
    public History() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        //---------------------
        this.setTitle("Project ACM. Formulario Visualizacao das Vendas Diarias ");
        //------------------------------------------------------------------------
        //--------------------------------------------------------
        URL url=this.getClass().getResource("folder/JFR.png");
        Image i =Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(i); 
        jTable2.setRowHeight(20);
        //--------------------------------------------------------
        CBO();
        teste();
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        valores = new javax.swing.JTextField();
        quant = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        JDate = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(247, 247, 247));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tabela de Vendas ");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 3));
        jLabel2.setOpaque(true);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel3.setText("Total de Vendas: ");

        txtTotal.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel4.setText("Total de Valores Recebidos:");

        valores.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        quant.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        quant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel5.setText("Qantidadades Vendidas:");

        jTable2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome da mercadoria:", "Preco:", "Quantidade:", "Desconto:", "Valor Recebido:", "Data:", "Hora:"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setMinWidth(250);
            jTable2.getColumnModel().getColumn(3).setMinWidth(100);
            jTable2.getColumnModel().getColumn(4).setMinWidth(100);
        }

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel1.setText("Data:");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/Erase.gif"))); // NOI18N
        jButton1.setText(" Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/List.gif"))); // NOI18N
        jButton2.setText("Preencher");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        JDate.setBackground(new java.awt.Color(255, 255, 255));
        JDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JDate.setDateFormatString("yyyy-MM-dd");
        JDate.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        JDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JDateMouseClicked(evt);
            }
        });
        JDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JDateKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JDateKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JDateKeyTyped(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/List.png"))); // NOI18N
        jButton3.setText("Ver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valores, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(jLabel5)
                        .addGap(12, 12, 12)
                        .addComponent(quant, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JDate, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jButton1)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(jButton3)
                    .addComponent(JDate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(valores, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(quant, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      this.teste();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
//        Menu f = new Menu();
//        f.setVisible(true);
//        f.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
//     int indice=jTable2.getSelectedRow();
//      TableModel model = jTable2.getModel();
//      this.index(indice); 
    }//GEN-LAST:event_jTable2MouseClicked

    private void JDateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JDateKeyReleased
     
    }//GEN-LAST:event_JDateKeyReleased

    private void JDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JDateKeyPressed
     
    }//GEN-LAST:event_JDateKeyPressed

    private void JDateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JDateKeyTyped
    
    }//GEN-LAST:event_JDateKeyTyped

    private void JDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JDateMouseClicked
   
    }//GEN-LAST:event_JDateMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     
        if(JDate.getDate()!=null){
        prencher();
        }else{JOptionPane.showMessageDialog(null,"Selecione uma data por favor","Falha",JOptionPane.WARNING_MESSAGE);}
    }//GEN-LAST:event_jButton3ActionPerformed


//public void index(int inde){
//   
//    LoginS a;
//    
//    a=(LoginS)x.get(inde);  
//       mostra(a);
//    
//    }
//
// public void mostra(LoginS a ){
//       JOptionPane.showMessageDialog(null,"Nome Produto: "+a.nomeProdutoV+"\n"
//               +"Preço Unitário: "+a.precoV+"\n"
//               +"Quantidade Vendida:  "+a.quantidadeV+"\n"
//               +"Valor de Venda: "+a.valorPagarV," Informações da Venda",JOptionPane.INFORMATION_MESSAGE);
//     }
//   
    
    
    int id,preco,q;
    String Nome;
    double pago,Cpagou,Trocos,Valorpagar,Desco;
    int total=0,Quant=0; double valo=0;
    //--------------------------------------------------------------------------
    
    public void teste(){
      total=0;  valo=0;  Quant=0;
      //========================================================================
        try{
           
           Class.forName(driver);
           this.con=DriverManager.getConnection(url, user, pass);
           sta=con.createStatement();
           //-------------------------------------------------------------------
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
           String [] linha= new String [7];
           //-------------------------------------------------------------------
          //Limpando Vector-------------------------------------------------
             for(int i =0;i<x.size();i++){
             x.removeAllElements();
             }
           //--------------------Limpando tabela----------------------------

          ((DefaultTableModel)jTable2.getModel()).setNumRows(0); 
          
           jTable2.updateUI(); 
           //---------------------------------------------------------------

         String query3="select * from descricao_vendas";
            
          this.resultado=sta.executeQuery(query3);
            
          while(resultado.next()){
             id=resultado.getInt("id_Tvendas");
             Nome = (resultado.getString("NomeP"));
             preco =resultado.getInt("Preco");
             q =resultado.getInt("quantidade");
             Valorpagar=resultado.getDouble("valor_pagar");
             Desco=resultado.getDouble("Desconto");
             Date Data=resultado.getDate("Data");
             Time time = resultado.getTime("Data");
             
             
             //--------------------------------------------
             vectorFood(Nome,preco,q,Desco,Valorpagar,Data,time);
             //--------------------------------------------
            linha[0]=Nome;
            linha[1]=preco+""; 
            linha[2]=q+""; 
            linha[3]=Desco+""; 
            linha[4]= Valorpagar+"";
            linha[5]=Data+"";
            linha[6]=time+"";
            
            model.addRow(linha); 
            total=total+1;
            valo=valo+Valorpagar;
            Quant=Quant+q;
          }
          
         txtTotal.setText(total+" Efectuadas");
         valores.setText(valo+" MT");
         quant.setText(Quant+" Unidades");
         
         
           }catch(SQLException e){
           JOptionPane.showMessageDialog(null, "Falha na busca das vendas","Pesquisa", JOptionPane.ERROR_MESSAGE);
           System.out.println(e);
       }catch(ClassNotFoundException e){
         JOptionPane.showMessageDialog(null, "Driver ");  
       }
       catch(NumberFormatException e){
           JOptionPane.showMessageDialog(null, "numero"); 
       }
        
    }
    
    
//     public void dois(int idV){
//      
//        
//        try{
//           
//           Class.forName(driver);
//           this.con=DriverManager.getConnection(url, user, pass);
//           sta=con.createStatement();
//         //---------------------------------------------------------------------
//           //-------------------------------------------------------------------
//            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
//           String [] linha= new String [6];
//           //-------------------------------------------------------------------
//           //--------------------Limpando tabela----------------------------
//
//          ((DefaultTableModel)jTable2.getModel()).setNumRows(0); 
//          
//           jTable2.updateUI(); 
//           //---------------------------------------------------------------
//         //---------------------------------------------------------------------    
//          String query5="select * from venda where id_Venda  = '"+ idV +"'"; 
//            
//          this.resultado=sta.executeQuery(query5);
//            
//            while(resultado.next()){
//            pago=resultado.getDouble("VRecebido");
//            Cpagou=resultado.getDouble("VPago");
//            Trocos =resultado.getDouble("Trocos");
//            
//            
//          //------------------------------------------------------
//            linha[0]=Nome;
//            linha[1]=preco+""; 
//            linha[2]=q+""; 
//            linha[3]= Valorpagar+"";
//            linha[4]=Cpagou+""; 
//            linha[5]=Trocos+"";
//           
//            
//           
//           model.addRow(linha);
//            
//            
//          }
//          
//           
//    
//           }catch(SQLException e){
//           JOptionPane.showMessageDialog(null, "Falha na busca da venda","Pesquisa", JOptionPane.ERROR_MESSAGE);
//           System.out.println(e);
//       }catch(ClassNotFoundException e){
//         JOptionPane.showMessageDialog(null, "Driver ");  
//       }
//       catch(NumberFormatException e){
//           JOptionPane.showMessageDialog(null, "numero"); 
//       }
//         
//    }
//    
//    
    
    
    
    
    
    
    
   
     public void prencher(){
      
         total=0;  valo=0;   Quant=0;
         LoginS a = new LoginS ();
       try{
           
           Date d = JDate.getDate(); 
           SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
           String date=sdf.format(d);
            
           Class.forName(driver);
           this.con=DriverManager.getConnection(url, user, pass);
           sta=con.createStatement();
           
           
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
           String [] linha= new String [7];
           //-------------------------------------------------------------------
           
           //--------------------Limpando tabela----------------------------

          ((DefaultTableModel)jTable2.getModel()).setNumRows(0); 
          
           jTable2.updateUI(); 
           //---------------------------------------------------------------
        
           for(int i=0;i<x.size();i++){
               
         a=(LoginS)x.get(i);
         String dat=sdf.format(a.dataV);
         
         if(dat.equals(date)){
             
             
            linha[0]=a.nomeProdutoV+"";
            linha[1]=a.precoV+""; 
            linha[2]=a.quantidadeV+""; 
            linha[3]=a.DescontoV+"";
            linha[4]=a.valorPagarV+""; 
            linha[5]=a.dataV+"";
            linha[6]=a.timeV+"";
           
            model.addRow(linha); 
           
            total=total+1;
            valo=valo+a.valorPagarV;
            Quant=Quant+a.quantidadeV;
         }
       
         txtTotal.setText(total+" Efectuadas");
         valores.setText(valo+" Mt");
         quant.setText(Quant+" Unidades");
           }
       }catch(SQLException e){
           JOptionPane.showMessageDialog(null, "Falha na busca das vendas","Pesquisa", JOptionPane.ERROR_MESSAGE);
           
       }catch(ClassNotFoundException e){
         JOptionPane.showMessageDialog(null, "Driver ");  
       }
       catch(NumberFormatException e){
           JOptionPane.showMessageDialog(null, "numero"); 
       }
        
        }
    
    
    
    
    
    
    
//  ---------------------------------Usando Vector------------------------------------------------------------------------------
      public void vectorFood(String nomeP,double preco,int quantidade,double Desconto,double Vpagar, Date data1,Time times){
        LoginS a = new LoginS();
       
        a.nomeProdutoV=nomeP;
        a.precoV=preco;
        a.quantidadeV=quantidade;
        a.DescontoV=Desconto;
        a.valorPagarV=Vpagar;
        a.dataV=data1; 
        a.timeV=times;
        
        x.addElement(a);
    }
      
     
    
    public void CBO(){
        try{
           
           Class.forName(driver);
           
          this.con=DriverManager.getConnection(url, user, pass);
           sta=con.createStatement();

           
           String query2="select distinct Date(Data) as Data from Descricao_Vendas";
            
          this.resultado=sta.executeQuery(query2);
            
          while(resultado.next()){
              
               
             
           //   cboData.addItem(resultado.getDate("Data"));
            
            }

       }catch(SQLException e){
           JOptionPane.showMessageDialog(null, "Falha na busca da data","Erro de Busca", JOptionPane.ERROR_MESSAGE);
           System.out.println(e.getMessage());
           
       }catch(ClassNotFoundException e){
         JOptionPane.showMessageDialog(null, "Driver ");  
       }
       catch(NumberFormatException e){
           JOptionPane.showMessageDialog(null, "numero"); 
       }    
        
        
    }
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new History().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField quant;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField valores;
    // End of variables declaration//GEN-END:variables
}
